services:
  hello-world:
    build: ./hello-world
    image: hello-world:latest
    container_name: hello-world
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./hello-world/app:/app